//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("dbGerenciadorModel", "FK_Agencia_Banco", "Banco", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Gerenciador.Data.Banco), "Agencia", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Gerenciador.Data.Agencia), true)]
[assembly: EdmRelationshipAttribute("dbGerenciadorModel", "FK_Conta_Agencia", "Agencia", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Gerenciador.Data.Agencia), "Conta", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Gerenciador.Data.Conta), true)]
[assembly: EdmRelationshipAttribute("dbGerenciadorModel", "FK_Movimento_Conta", "Conta", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Gerenciador.Data.Conta), "Movimento", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Gerenciador.Data.Movimento), true)]
[assembly: EdmRelationshipAttribute("dbGerenciadorModel", "FK_Titulo_Conta", "Conta", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Gerenciador.Data.Conta), "Titulo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Gerenciador.Data.Titulo), true)]
[assembly: EdmRelationshipAttribute("dbGerenciadorModel", "FK_Movimento_Titulo", "Titulo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Gerenciador.Data.Titulo), "Movimento", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Gerenciador.Data.Movimento), true)]
[assembly: EdmRelationshipAttribute("dbGerenciadorModel", "FK_Titulo_Natureza", "Natureza", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Gerenciador.Data.Natureza), "Titulo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Gerenciador.Data.Titulo), true)]
[assembly: EdmRelationshipAttribute("dbGerenciadorModel", "FK_Titulo_Relacao", "Relacao", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Gerenciador.Data.Relacao), "Titulo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Gerenciador.Data.Titulo), true)]

#endregion

namespace Gerenciador.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class dbGerenciadorEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new dbGerenciadorEntities object using the connection string found in the 'dbGerenciadorEntities' section of the application configuration file.
        /// </summary>
        public dbGerenciadorEntities() : base("name=dbGerenciadorEntities", "dbGerenciadorEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbGerenciadorEntities object.
        /// </summary>
        public dbGerenciadorEntities(string connectionString) : base(connectionString, "dbGerenciadorEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new dbGerenciadorEntities object.
        /// </summary>
        public dbGerenciadorEntities(EntityConnection connection) : base(connection, "dbGerenciadorEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Agencia> Agencia
        {
            get
            {
                if ((_Agencia == null))
                {
                    _Agencia = base.CreateObjectSet<Agencia>("Agencia");
                }
                return _Agencia;
            }
        }
        private ObjectSet<Agencia> _Agencia;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Banco> Banco
        {
            get
            {
                if ((_Banco == null))
                {
                    _Banco = base.CreateObjectSet<Banco>("Banco");
                }
                return _Banco;
            }
        }
        private ObjectSet<Banco> _Banco;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Conta> Conta
        {
            get
            {
                if ((_Conta == null))
                {
                    _Conta = base.CreateObjectSet<Conta>("Conta");
                }
                return _Conta;
            }
        }
        private ObjectSet<Conta> _Conta;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Movimento> Movimento
        {
            get
            {
                if ((_Movimento == null))
                {
                    _Movimento = base.CreateObjectSet<Movimento>("Movimento");
                }
                return _Movimento;
            }
        }
        private ObjectSet<Movimento> _Movimento;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Natureza> Natureza
        {
            get
            {
                if ((_Natureza == null))
                {
                    _Natureza = base.CreateObjectSet<Natureza>("Natureza");
                }
                return _Natureza;
            }
        }
        private ObjectSet<Natureza> _Natureza;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Relacao> Relacao
        {
            get
            {
                if ((_Relacao == null))
                {
                    _Relacao = base.CreateObjectSet<Relacao>("Relacao");
                }
                return _Relacao;
            }
        }
        private ObjectSet<Relacao> _Relacao;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<email> email
        {
            get
            {
                if ((_email == null))
                {
                    _email = base.CreateObjectSet<email>("email");
                }
                return _email;
            }
        }
        private ObjectSet<email> _email;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Titulo> Titulo
        {
            get
            {
                if ((_Titulo == null))
                {
                    _Titulo = base.CreateObjectSet<Titulo>("Titulo");
                }
                return _Titulo;
            }
        }
        private ObjectSet<Titulo> _Titulo;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<usuario> usuario
        {
            get
            {
                if ((_usuario == null))
                {
                    _usuario = base.CreateObjectSet<usuario>("usuario");
                }
                return _usuario;
            }
        }
        private ObjectSet<usuario> _usuario;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Agencia EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAgencia(Agencia agencia)
        {
            base.AddObject("Agencia", agencia);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Banco EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBanco(Banco banco)
        {
            base.AddObject("Banco", banco);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Conta EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToConta(Conta conta)
        {
            base.AddObject("Conta", conta);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Movimento EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMovimento(Movimento movimento)
        {
            base.AddObject("Movimento", movimento);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Natureza EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNatureza(Natureza natureza)
        {
            base.AddObject("Natureza", natureza);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Relacao EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRelacao(Relacao relacao)
        {
            base.AddObject("Relacao", relacao);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the email EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToemail(email email)
        {
            base.AddObject("email", email);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Titulo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTitulo(Titulo titulo)
        {
            base.AddObject("Titulo", titulo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the usuario EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTousuario(usuario usuario)
        {
            base.AddObject("usuario", usuario);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbGerenciadorModel", Name="Agencia")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Agencia : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Agencia object.
        /// </summary>
        /// <param name="numero">Initial value of the numero property.</param>
        /// <param name="banco">Initial value of the banco property.</param>
        /// <param name="descricao">Initial value of the descricao property.</param>
        public static Agencia CreateAgencia(global::System.Int32 numero, global::System.Int32 banco, global::System.String descricao)
        {
            Agencia agencia = new Agencia();
            agencia.numero = numero;
            agencia.banco = banco;
            agencia.descricao = descricao;
            return agencia;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 numero
        {
            get
            {
                return _numero;
            }
            set
            {
                if (_numero != value)
                {
                    OnnumeroChanging(value);
                    ReportPropertyChanging("numero");
                    _numero = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("numero");
                    OnnumeroChanged();
                }
            }
        }
        private global::System.Int32 _numero;
        partial void OnnumeroChanging(global::System.Int32 value);
        partial void OnnumeroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 banco
        {
            get
            {
                return _banco;
            }
            set
            {
                OnbancoChanging(value);
                ReportPropertyChanging("banco");
                _banco = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("banco");
                OnbancoChanged();
            }
        }
        private global::System.Int32 _banco;
        partial void OnbancoChanging(global::System.Int32 value);
        partial void OnbancoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descricao
        {
            get
            {
                return _descricao;
            }
            set
            {
                OndescricaoChanging(value);
                ReportPropertyChanging("descricao");
                _descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descricao");
                OndescricaoChanged();
            }
        }
        private global::System.String _descricao;
        partial void OndescricaoChanging(global::System.String value);
        partial void OndescricaoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbGerenciadorModel", "FK_Agencia_Banco", "Banco")]
        public Banco Banco1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Banco>("dbGerenciadorModel.FK_Agencia_Banco", "Banco").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Banco>("dbGerenciadorModel.FK_Agencia_Banco", "Banco").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Banco> Banco1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Banco>("dbGerenciadorModel.FK_Agencia_Banco", "Banco");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Banco>("dbGerenciadorModel.FK_Agencia_Banco", "Banco", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbGerenciadorModel", "FK_Conta_Agencia", "Conta")]
        public EntityCollection<Conta> Conta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Conta>("dbGerenciadorModel.FK_Conta_Agencia", "Conta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Conta>("dbGerenciadorModel.FK_Conta_Agencia", "Conta", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbGerenciadorModel", Name="Banco")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Banco : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Banco object.
        /// </summary>
        /// <param name="numero">Initial value of the numero property.</param>
        /// <param name="descricao">Initial value of the descricao property.</param>
        public static Banco CreateBanco(global::System.Int32 numero, global::System.String descricao)
        {
            Banco banco = new Banco();
            banco.numero = numero;
            banco.descricao = descricao;
            return banco;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 numero
        {
            get
            {
                return _numero;
            }
            set
            {
                if (_numero != value)
                {
                    OnnumeroChanging(value);
                    ReportPropertyChanging("numero");
                    _numero = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("numero");
                    OnnumeroChanged();
                }
            }
        }
        private global::System.Int32 _numero;
        partial void OnnumeroChanging(global::System.Int32 value);
        partial void OnnumeroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descricao
        {
            get
            {
                return _descricao;
            }
            set
            {
                OndescricaoChanging(value);
                ReportPropertyChanging("descricao");
                _descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descricao");
                OndescricaoChanged();
            }
        }
        private global::System.String _descricao;
        partial void OndescricaoChanging(global::System.String value);
        partial void OndescricaoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbGerenciadorModel", "FK_Agencia_Banco", "Agencia")]
        public EntityCollection<Agencia> Agencia
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Agencia>("dbGerenciadorModel.FK_Agencia_Banco", "Agencia");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Agencia>("dbGerenciadorModel.FK_Agencia_Banco", "Agencia", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbGerenciadorModel", Name="Conta")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Conta : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Conta object.
        /// </summary>
        /// <param name="numero">Initial value of the numero property.</param>
        /// <param name="agencia">Initial value of the agencia property.</param>
        /// <param name="descricao">Initial value of the descricao property.</param>
        /// <param name="saldo">Initial value of the saldo property.</param>
        public static Conta CreateConta(global::System.Int32 numero, global::System.Int32 agencia, global::System.String descricao, global::System.Decimal saldo)
        {
            Conta conta = new Conta();
            conta.numero = numero;
            conta.agencia = agencia;
            conta.descricao = descricao;
            conta.saldo = saldo;
            return conta;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 numero
        {
            get
            {
                return _numero;
            }
            set
            {
                if (_numero != value)
                {
                    OnnumeroChanging(value);
                    ReportPropertyChanging("numero");
                    _numero = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("numero");
                    OnnumeroChanged();
                }
            }
        }
        private global::System.Int32 _numero;
        partial void OnnumeroChanging(global::System.Int32 value);
        partial void OnnumeroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 agencia
        {
            get
            {
                return _agencia;
            }
            set
            {
                OnagenciaChanging(value);
                ReportPropertyChanging("agencia");
                _agencia = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("agencia");
                OnagenciaChanged();
            }
        }
        private global::System.Int32 _agencia;
        partial void OnagenciaChanging(global::System.Int32 value);
        partial void OnagenciaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descricao
        {
            get
            {
                return _descricao;
            }
            set
            {
                OndescricaoChanging(value);
                ReportPropertyChanging("descricao");
                _descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descricao");
                OndescricaoChanged();
            }
        }
        private global::System.String _descricao;
        partial void OndescricaoChanging(global::System.String value);
        partial void OndescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal saldo
        {
            get
            {
                return _saldo;
            }
            set
            {
                OnsaldoChanging(value);
                ReportPropertyChanging("saldo");
                _saldo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("saldo");
                OnsaldoChanged();
            }
        }
        private global::System.Decimal _saldo;
        partial void OnsaldoChanging(global::System.Decimal value);
        partial void OnsaldoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> saldoInicial
        {
            get
            {
                return _saldoInicial;
            }
            set
            {
                OnsaldoInicialChanging(value);
                ReportPropertyChanging("saldoInicial");
                _saldoInicial = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("saldoInicial");
                OnsaldoInicialChanged();
            }
        }
        private Nullable<global::System.Decimal> _saldoInicial;
        partial void OnsaldoInicialChanging(Nullable<global::System.Decimal> value);
        partial void OnsaldoInicialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> data_criacao
        {
            get
            {
                return _data_criacao;
            }
            set
            {
                Ondata_criacaoChanging(value);
                ReportPropertyChanging("data_criacao");
                _data_criacao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("data_criacao");
                Ondata_criacaoChanged();
            }
        }
        private Nullable<global::System.DateTime> _data_criacao;
        partial void Ondata_criacaoChanging(Nullable<global::System.DateTime> value);
        partial void Ondata_criacaoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbGerenciadorModel", "FK_Conta_Agencia", "Agencia")]
        public Agencia Agencia1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Agencia>("dbGerenciadorModel.FK_Conta_Agencia", "Agencia").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Agencia>("dbGerenciadorModel.FK_Conta_Agencia", "Agencia").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Agencia> Agencia1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Agencia>("dbGerenciadorModel.FK_Conta_Agencia", "Agencia");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Agencia>("dbGerenciadorModel.FK_Conta_Agencia", "Agencia", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbGerenciadorModel", "FK_Movimento_Conta", "Movimento")]
        public EntityCollection<Movimento> Movimento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Movimento>("dbGerenciadorModel.FK_Movimento_Conta", "Movimento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Movimento>("dbGerenciadorModel.FK_Movimento_Conta", "Movimento", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbGerenciadorModel", "FK_Titulo_Conta", "Titulo")]
        public EntityCollection<Titulo> Titulo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Titulo>("dbGerenciadorModel.FK_Titulo_Conta", "Titulo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Titulo>("dbGerenciadorModel.FK_Titulo_Conta", "Titulo", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbGerenciadorModel", Name="email")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class email : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new email object.
        /// </summary>
        /// <param name="email1">Initial value of the email1 property.</param>
        /// <param name="smtp">Initial value of the smtp property.</param>
        /// <param name="porta">Initial value of the porta property.</param>
        /// <param name="senha">Initial value of the senha property.</param>
        /// <param name="observacao">Initial value of the observacao property.</param>
        public static email Createemail(global::System.String email1, global::System.String smtp, global::System.Int32 porta, global::System.String senha, global::System.String observacao)
        {
            email email = new email();
            email.email1 = email1;
            email.smtp = smtp;
            email.porta = porta;
            email.senha = senha;
            email.observacao = observacao;
            return email;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email1
        {
            get
            {
                return _email1;
            }
            set
            {
                if (_email1 != value)
                {
                    Onemail1Changing(value);
                    ReportPropertyChanging("email1");
                    _email1 = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("email1");
                    Onemail1Changed();
                }
            }
        }
        private global::System.String _email1;
        partial void Onemail1Changing(global::System.String value);
        partial void Onemail1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String smtp
        {
            get
            {
                return _smtp;
            }
            set
            {
                OnsmtpChanging(value);
                ReportPropertyChanging("smtp");
                _smtp = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("smtp");
                OnsmtpChanged();
            }
        }
        private global::System.String _smtp;
        partial void OnsmtpChanging(global::System.String value);
        partial void OnsmtpChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 porta
        {
            get
            {
                return _porta;
            }
            set
            {
                OnportaChanging(value);
                ReportPropertyChanging("porta");
                _porta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("porta");
                OnportaChanged();
            }
        }
        private global::System.Int32 _porta;
        partial void OnportaChanging(global::System.Int32 value);
        partial void OnportaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String senha
        {
            get
            {
                return _senha;
            }
            set
            {
                OnsenhaChanging(value);
                ReportPropertyChanging("senha");
                _senha = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("senha");
                OnsenhaChanged();
            }
        }
        private global::System.String _senha;
        partial void OnsenhaChanging(global::System.String value);
        partial void OnsenhaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String observacao
        {
            get
            {
                return _observacao;
            }
            set
            {
                OnobservacaoChanging(value);
                ReportPropertyChanging("observacao");
                _observacao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("observacao");
                OnobservacaoChanged();
            }
        }
        private global::System.String _observacao;
        partial void OnobservacaoChanging(global::System.String value);
        partial void OnobservacaoChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbGerenciadorModel", Name="Movimento")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Movimento : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Movimento object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="data">Initial value of the data property.</param>
        /// <param name="tipo">Initial value of the tipo property.</param>
        /// <param name="valor">Initial value of the valor property.</param>
        /// <param name="numero">Initial value of the numero property.</param>
        /// <param name="descricao">Initial value of the descricao property.</param>
        /// <param name="conta">Initial value of the conta property.</param>
        public static Movimento CreateMovimento(global::System.Int32 id, global::System.DateTime data, global::System.String tipo, global::System.Decimal valor, global::System.String numero, global::System.String descricao, global::System.Int32 conta)
        {
            Movimento movimento = new Movimento();
            movimento.id = id;
            movimento.data = data;
            movimento.tipo = tipo;
            movimento.valor = valor;
            movimento.numero = numero;
            movimento.descricao = descricao;
            movimento.conta = conta;
            return movimento;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime data
        {
            get
            {
                return _data;
            }
            set
            {
                OndataChanging(value);
                ReportPropertyChanging("data");
                _data = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("data");
                OndataChanged();
            }
        }
        private global::System.DateTime _data;
        partial void OndataChanging(global::System.DateTime value);
        partial void OndataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tipo
        {
            get
            {
                return _tipo;
            }
            set
            {
                OntipoChanging(value);
                ReportPropertyChanging("tipo");
                _tipo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tipo");
                OntipoChanged();
            }
        }
        private global::System.String _tipo;
        partial void OntipoChanging(global::System.String value);
        partial void OntipoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal valor
        {
            get
            {
                return _valor;
            }
            set
            {
                OnvalorChanging(value);
                ReportPropertyChanging("valor");
                _valor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("valor");
                OnvalorChanged();
            }
        }
        private global::System.Decimal _valor;
        partial void OnvalorChanging(global::System.Decimal value);
        partial void OnvalorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String numero
        {
            get
            {
                return _numero;
            }
            set
            {
                OnnumeroChanging(value);
                ReportPropertyChanging("numero");
                _numero = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("numero");
                OnnumeroChanged();
            }
        }
        private global::System.String _numero;
        partial void OnnumeroChanging(global::System.String value);
        partial void OnnumeroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descricao
        {
            get
            {
                return _descricao;
            }
            set
            {
                OndescricaoChanging(value);
                ReportPropertyChanging("descricao");
                _descricao = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descricao");
                OndescricaoChanged();
            }
        }
        private global::System.String _descricao;
        partial void OndescricaoChanging(global::System.String value);
        partial void OndescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 conta
        {
            get
            {
                return _conta;
            }
            set
            {
                OncontaChanging(value);
                ReportPropertyChanging("conta");
                _conta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("conta");
                OncontaChanged();
            }
        }
        private global::System.Int32 _conta;
        partial void OncontaChanging(global::System.Int32 value);
        partial void OncontaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> saldo
        {
            get
            {
                return _saldo;
            }
            set
            {
                OnsaldoChanging(value);
                ReportPropertyChanging("saldo");
                _saldo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("saldo");
                OnsaldoChanged();
            }
        }
        private Nullable<global::System.Decimal> _saldo;
        partial void OnsaldoChanging(Nullable<global::System.Decimal> value);
        partial void OnsaldoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> id_titulo
        {
            get
            {
                return _id_titulo;
            }
            set
            {
                Onid_tituloChanging(value);
                ReportPropertyChanging("id_titulo");
                _id_titulo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_titulo");
                Onid_tituloChanged();
            }
        }
        private Nullable<global::System.Int32> _id_titulo;
        partial void Onid_tituloChanging(Nullable<global::System.Int32> value);
        partial void Onid_tituloChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbGerenciadorModel", "FK_Movimento_Conta", "Conta")]
        public Conta Conta1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Conta>("dbGerenciadorModel.FK_Movimento_Conta", "Conta").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Conta>("dbGerenciadorModel.FK_Movimento_Conta", "Conta").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Conta> Conta1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Conta>("dbGerenciadorModel.FK_Movimento_Conta", "Conta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Conta>("dbGerenciadorModel.FK_Movimento_Conta", "Conta", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbGerenciadorModel", "FK_Movimento_Titulo", "Titulo")]
        public Titulo Titulo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Titulo>("dbGerenciadorModel.FK_Movimento_Titulo", "Titulo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Titulo>("dbGerenciadorModel.FK_Movimento_Titulo", "Titulo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Titulo> TituloReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Titulo>("dbGerenciadorModel.FK_Movimento_Titulo", "Titulo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Titulo>("dbGerenciadorModel.FK_Movimento_Titulo", "Titulo", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbGerenciadorModel", Name="Natureza")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Natureza : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Natureza object.
        /// </summary>
        /// <param name="nome">Initial value of the nome property.</param>
        public static Natureza CreateNatureza(global::System.String nome)
        {
            Natureza natureza = new Natureza();
            natureza.nome = nome;
            return natureza;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nome
        {
            get
            {
                return _nome;
            }
            set
            {
                if (_nome != value)
                {
                    OnnomeChanging(value);
                    ReportPropertyChanging("nome");
                    _nome = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("nome");
                    OnnomeChanged();
                }
            }
        }
        private global::System.String _nome;
        partial void OnnomeChanging(global::System.String value);
        partial void OnnomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descricao
        {
            get
            {
                return _descricao;
            }
            set
            {
                OndescricaoChanging(value);
                ReportPropertyChanging("descricao");
                _descricao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("descricao");
                OndescricaoChanged();
            }
        }
        private global::System.String _descricao;
        partial void OndescricaoChanging(global::System.String value);
        partial void OndescricaoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbGerenciadorModel", "FK_Titulo_Natureza", "Titulo")]
        public EntityCollection<Titulo> Titulo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Titulo>("dbGerenciadorModel.FK_Titulo_Natureza", "Titulo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Titulo>("dbGerenciadorModel.FK_Titulo_Natureza", "Titulo", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbGerenciadorModel", Name="Relacao")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Relacao : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Relacao object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="nome">Initial value of the Nome property.</param>
        /// <param name="tipo">Initial value of the Tipo property.</param>
        public static Relacao CreateRelacao(global::System.Int32 id, global::System.String nome, global::System.String tipo)
        {
            Relacao relacao = new Relacao();
            relacao.id = id;
            relacao.Nome = nome;
            relacao.Tipo = tipo;
            return relacao;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nome
        {
            get
            {
                return _Nome;
            }
            set
            {
                OnNomeChanging(value);
                ReportPropertyChanging("Nome");
                _Nome = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nome");
                OnNomeChanged();
            }
        }
        private global::System.String _Nome;
        partial void OnNomeChanging(global::System.String value);
        partial void OnNomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Tipo
        {
            get
            {
                return _Tipo;
            }
            set
            {
                OnTipoChanging(value);
                ReportPropertyChanging("Tipo");
                _Tipo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Tipo");
                OnTipoChanged();
            }
        }
        private global::System.String _Tipo;
        partial void OnTipoChanging(global::System.String value);
        partial void OnTipoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbGerenciadorModel", "FK_Titulo_Relacao", "Titulo")]
        public EntityCollection<Titulo> Titulo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Titulo>("dbGerenciadorModel.FK_Titulo_Relacao", "Titulo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Titulo>("dbGerenciadorModel.FK_Titulo_Relacao", "Titulo", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbGerenciadorModel", Name="Titulo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Titulo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Titulo object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="numero">Initial value of the numero property.</param>
        /// <param name="relacao">Initial value of the relacao property.</param>
        /// <param name="tipo">Initial value of the tipo property.</param>
        /// <param name="qtd_parcela">Initial value of the qtd_parcela property.</param>
        /// <param name="valor">Initial value of the valor property.</param>
        /// <param name="vencimento">Initial value of the vencimento property.</param>
        /// <param name="natureza">Initial value of the natureza property.</param>
        public static Titulo CreateTitulo(global::System.Int32 id, global::System.Int32 numero, global::System.Int32 relacao, global::System.String tipo, global::System.Int32 qtd_parcela, global::System.Decimal valor, global::System.DateTime vencimento, global::System.String natureza)
        {
            Titulo titulo = new Titulo();
            titulo.id = id;
            titulo.numero = numero;
            titulo.relacao = relacao;
            titulo.tipo = tipo;
            titulo.qtd_parcela = qtd_parcela;
            titulo.valor = valor;
            titulo.vencimento = vencimento;
            titulo.natureza = natureza;
            return titulo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 numero
        {
            get
            {
                return _numero;
            }
            set
            {
                OnnumeroChanging(value);
                ReportPropertyChanging("numero");
                _numero = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("numero");
                OnnumeroChanged();
            }
        }
        private global::System.Int32 _numero;
        partial void OnnumeroChanging(global::System.Int32 value);
        partial void OnnumeroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 relacao
        {
            get
            {
                return _relacao;
            }
            set
            {
                OnrelacaoChanging(value);
                ReportPropertyChanging("relacao");
                _relacao = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("relacao");
                OnrelacaoChanged();
            }
        }
        private global::System.Int32 _relacao;
        partial void OnrelacaoChanging(global::System.Int32 value);
        partial void OnrelacaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tipo
        {
            get
            {
                return _tipo;
            }
            set
            {
                OntipoChanging(value);
                ReportPropertyChanging("tipo");
                _tipo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tipo");
                OntipoChanged();
            }
        }
        private global::System.String _tipo;
        partial void OntipoChanging(global::System.String value);
        partial void OntipoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 qtd_parcela
        {
            get
            {
                return _qtd_parcela;
            }
            set
            {
                Onqtd_parcelaChanging(value);
                ReportPropertyChanging("qtd_parcela");
                _qtd_parcela = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("qtd_parcela");
                Onqtd_parcelaChanged();
            }
        }
        private global::System.Int32 _qtd_parcela;
        partial void Onqtd_parcelaChanging(global::System.Int32 value);
        partial void Onqtd_parcelaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal valor
        {
            get
            {
                return _valor;
            }
            set
            {
                OnvalorChanging(value);
                ReportPropertyChanging("valor");
                _valor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("valor");
                OnvalorChanged();
            }
        }
        private global::System.Decimal _valor;
        partial void OnvalorChanging(global::System.Decimal value);
        partial void OnvalorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime vencimento
        {
            get
            {
                return _vencimento;
            }
            set
            {
                OnvencimentoChanging(value);
                ReportPropertyChanging("vencimento");
                _vencimento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("vencimento");
                OnvencimentoChanged();
            }
        }
        private global::System.DateTime _vencimento;
        partial void OnvencimentoChanging(global::System.DateTime value);
        partial void OnvencimentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String natureza
        {
            get
            {
                return _natureza;
            }
            set
            {
                OnnaturezaChanging(value);
                ReportPropertyChanging("natureza");
                _natureza = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("natureza");
                OnnaturezaChanged();
            }
        }
        private global::System.String _natureza;
        partial void OnnaturezaChanging(global::System.String value);
        partial void OnnaturezaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String baixado
        {
            get
            {
                return _baixado;
            }
            set
            {
                OnbaixadoChanging(value);
                ReportPropertyChanging("baixado");
                _baixado = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("baixado");
                OnbaixadoChanged();
            }
        }
        private global::System.String _baixado;
        partial void OnbaixadoChanging(global::System.String value);
        partial void OnbaixadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dta_baixa
        {
            get
            {
                return _dta_baixa;
            }
            set
            {
                Ondta_baixaChanging(value);
                ReportPropertyChanging("dta_baixa");
                _dta_baixa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dta_baixa");
                Ondta_baixaChanged();
            }
        }
        private Nullable<global::System.DateTime> _dta_baixa;
        partial void Ondta_baixaChanging(Nullable<global::System.DateTime> value);
        partial void Ondta_baixaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> vlr_pagamento
        {
            get
            {
                return _vlr_pagamento;
            }
            set
            {
                Onvlr_pagamentoChanging(value);
                ReportPropertyChanging("vlr_pagamento");
                _vlr_pagamento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("vlr_pagamento");
                Onvlr_pagamentoChanged();
            }
        }
        private Nullable<global::System.Decimal> _vlr_pagamento;
        partial void Onvlr_pagamentoChanging(Nullable<global::System.Decimal> value);
        partial void Onvlr_pagamentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descricao
        {
            get
            {
                return _descricao;
            }
            set
            {
                OndescricaoChanging(value);
                ReportPropertyChanging("descricao");
                _descricao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("descricao");
                OndescricaoChanged();
            }
        }
        private global::System.String _descricao;
        partial void OndescricaoChanging(global::System.String value);
        partial void OndescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> conta_baixa
        {
            get
            {
                return _conta_baixa;
            }
            set
            {
                Onconta_baixaChanging(value);
                ReportPropertyChanging("conta_baixa");
                _conta_baixa = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("conta_baixa");
                Onconta_baixaChanged();
            }
        }
        private Nullable<global::System.Int32> _conta_baixa;
        partial void Onconta_baixaChanging(Nullable<global::System.Int32> value);
        partial void Onconta_baixaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> parcela
        {
            get
            {
                return _parcela;
            }
            set
            {
                OnparcelaChanging(value);
                ReportPropertyChanging("parcela");
                _parcela = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("parcela");
                OnparcelaChanged();
            }
        }
        private Nullable<global::System.Int32> _parcela;
        partial void OnparcelaChanging(Nullable<global::System.Int32> value);
        partial void OnparcelaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String codigoBarras
        {
            get
            {
                return _codigoBarras;
            }
            set
            {
                OncodigoBarrasChanging(value);
                ReportPropertyChanging("codigoBarras");
                _codigoBarras = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("codigoBarras");
                OncodigoBarrasChanged();
            }
        }
        private global::System.String _codigoBarras;
        partial void OncodigoBarrasChanging(global::System.String value);
        partial void OncodigoBarrasChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbGerenciadorModel", "FK_Titulo_Conta", "Conta")]
        public Conta Conta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Conta>("dbGerenciadorModel.FK_Titulo_Conta", "Conta").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Conta>("dbGerenciadorModel.FK_Titulo_Conta", "Conta").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Conta> ContaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Conta>("dbGerenciadorModel.FK_Titulo_Conta", "Conta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Conta>("dbGerenciadorModel.FK_Titulo_Conta", "Conta", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbGerenciadorModel", "FK_Movimento_Titulo", "Movimento")]
        public EntityCollection<Movimento> Movimento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Movimento>("dbGerenciadorModel.FK_Movimento_Titulo", "Movimento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Movimento>("dbGerenciadorModel.FK_Movimento_Titulo", "Movimento", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbGerenciadorModel", "FK_Titulo_Natureza", "Natureza")]
        public Natureza Natureza1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Natureza>("dbGerenciadorModel.FK_Titulo_Natureza", "Natureza").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Natureza>("dbGerenciadorModel.FK_Titulo_Natureza", "Natureza").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Natureza> Natureza1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Natureza>("dbGerenciadorModel.FK_Titulo_Natureza", "Natureza");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Natureza>("dbGerenciadorModel.FK_Titulo_Natureza", "Natureza", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("dbGerenciadorModel", "FK_Titulo_Relacao", "Relacao")]
        public Relacao Relacao1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Relacao>("dbGerenciadorModel.FK_Titulo_Relacao", "Relacao").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Relacao>("dbGerenciadorModel.FK_Titulo_Relacao", "Relacao").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Relacao> Relacao1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Relacao>("dbGerenciadorModel.FK_Titulo_Relacao", "Relacao");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Relacao>("dbGerenciadorModel.FK_Titulo_Relacao", "Relacao", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbGerenciadorModel", Name="usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class usuario : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new usuario object.
        /// </summary>
        /// <param name="nome">Initial value of the nome property.</param>
        /// <param name="senha">Initial value of the senha property.</param>
        public static usuario Createusuario(global::System.String nome, global::System.String senha)
        {
            usuario usuario = new usuario();
            usuario.nome = nome;
            usuario.senha = senha;
            return usuario;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nome
        {
            get
            {
                return _nome;
            }
            set
            {
                if (_nome != value)
                {
                    OnnomeChanging(value);
                    ReportPropertyChanging("nome");
                    _nome = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("nome");
                    OnnomeChanged();
                }
            }
        }
        private global::System.String _nome;
        partial void OnnomeChanging(global::System.String value);
        partial void OnnomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String senha
        {
            get
            {
                return _senha;
            }
            set
            {
                OnsenhaChanging(value);
                ReportPropertyChanging("senha");
                _senha = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("senha");
                OnsenhaChanged();
            }
        }
        private global::System.String _senha;
        partial void OnsenhaChanging(global::System.String value);
        partial void OnsenhaChanged();

        #endregion
    
    }

    #endregion
    
}
